### ISSUE TITLE
CVD2014 dataset

### ISSUE THREAD

**Issue by threeds** [lidq92/VSFA#1]
CVD2014 dataset is not avaliable on the website. Can you provide the dataset?

**Comment by lidq92** [comment]
@threeds You may email the owner of CVD2014 first. If you do not get the response in a week, you may reply to me here again and leave your email address. I may share it with you for research purpose only. (I have to check whether I have the permission to share it with you for your research only.)

**Comment by lidq92** [comment]
Hi @threeds 
When I searched on the Internet, I found [this url](https://zenodo.org/record/2646315#.XVLFDy2B0cg), and you can download CVD2014 here.

**Comment by threeds** [comment]
@lidq92  Thanks! It really helps me.
