### ISSUE TITLE
Use this method need the super memory?

### ISSUE THREAD

**Issue by JavanTang** [lidq92/VSFA#12]

**Comment by JavanTang** [comment]
Input:
`!python /content/VSFA/test_demo.py --video_path='/content/VSFA/ACMMM_2019_supplementary_44/video pair/better-MAH_02693_8s.mp4' --model_path=/content/VSFA/models/VSFA.pt
`
output:
`RuntimeError: CUDA out of memory. Tried to allocate 3.96 GiB (GPU 0; 15.90 GiB total capacity; 9.73 GiB already allocated; 2.47 GiB free; 12.72 GiB reserved in total by PyTorch)`

**Comment by JavanTang** [comment]
This question is my computer configuration or using way?

**Comment by lidq92** [comment]
@JavanTang You should read the `test_demo.py` carefully.
Or at least you can run `python test_demo.py --help` to get more information.
Actually, you can set `frame_batch_size` to 16, then it only needs about 9G GPU memory.

The supplementary video pairs are just used for illustrating the motivation of this paper.
We provide the `test_demo.py` with the `test.mp4` example (which has a smaller resolution than my supplementary video pairs, so it can be run with default `frame_batch_size`, 32).

To save GPU memory, a smaller `frame_batch_size` is preferred.

**Comment by JavanTang** [comment]
@lidq92 Well. Video length increases, can increase memory? Try to test 32 seconds video on my side, but my memory more than 12 gb, is this normal?

**Comment by lidq92** [comment]
@JavanTang  Read the `test_demo.py`, or at least I strongly suggest you run python `test_demo.py --help` to get more information.

It is obvious that the video spatial resolution has an effect on the GPU memory.
"It only needs about 9G GPU memory for a **1080P** video with setting `frame_batch_size=16`.

**Comment by JavanTang** [comment]
@lidq92 Ok, thank you
