### ISSUE TITLE
global std pooling ?

### ISSUE THREAD

**Issue by ucas010** [lidq92/VSFA#14]
hi，大佬
这个[操作](https://github.com/pRecSys/VSFA/blob/master/CNNfeatures.py#L87)
```
def global_std_pool2d(x):
    """2D global standard variation pooling"""
    return torch.std(x.view(x.size()[0], x.size()[1], -1, 1),
                     dim=2, keepdim=True)
```
这个std的池化有什么参考吗？我看论文似乎没说啊，
最后两个维度HW为什么还要保持呢？
多谢。

**Comment by lidq92** [comment]
@ucas010 你可能需要再仔细看一下论文原文以及相关地方的引用：不止说了，还在多处涉及，方法框图中有显示，而且相关工作中还有相关文章的引用。

也希望你先了解一下PyTorch代码，或者你可以用debug模式输出一下你不理解的地方。`x.view(x.size()[0], x.size()[1], -1, 1)`这个操作把形状改为`(N,C,H*W,1)`这样在`dim=2`算std就相当于在每一个特征图分别算std，你接着往下看mean和std对应的特征拼接的`cat`操作就知道了，之后这两个维度也`.squeeze()`掉了。
当然也可以把mean，std中HW对应的维度丢掉后再cat，这些只是实现细节，我觉得没什么差别。
更关键的建议是：你可以先把论文看完之后再看代码，这样也许会更清晰点。或者你可以参考一些标准模板的做法先把代码的不同部分分开之后再逐步看。

祝好。

**Comment by ucas010** [comment]
多谢。
