### ISSUE TITLE
Questions about 'data_info_maker.m' and the epochs

### ISSUE THREAD

**Issue by stillbetter** [lidq92/VSFA#16]
Thanks for the code. But when I reproduce the paper,I found that in 'KoNViD-1k' dataset, the video clips is '5319047612.mp4',but the code in data_info_maker.m is to get the file_name like '5319047612_cut_centercrop_960x540_8s.mp4' ,thus will return erro 

FileNotFoundError: [Errno 2] No such file or directory: './data/KoNViD-1k/KoNViD_1k_videos/8536919744    _original_centercrop_960x540_8s.mp4'

I don't know if the code is wrong or the dataset I downloaded has a different file name

**Comment by lidq92** [comment]
@stillbetter There exists several versions of this dataset. 

I downloaded this dataset a long time ago. 
During the time, the dataset owner had renamed the video clips, i.e., simplifying the name. 
You can re-make the `KoNViD-1kinfo.mat` with the right CSV file.
What you need to ensure is every video clip has its truly corresponding MOS.

Now I cannot access [konvid-1k-database](http://database.mmsp-kn.de/konvid-1k-database.html). You may ask the dataset owner for confirmation.

**Comment by stillbetter** [comment]
Got it.Thanks!

**Comment by stillbetter** [comment]
Sorry for another question, I check the log file, I found the SROCC/PLCC/KROCC can reach a peak performance at around 100 epochs, then the figures get bad . Is that a little bit overfitting? Thanks!

**Comment by lidq92** [comment]
@stillbetter We use a **standard** procedure, _i.e._, training the model on the train data, saving the model based on validation data (That is, we monitor the validation performance, then save the best model.), and then testing the saved model on the test data.

If you see the training loss becomes smaller and smaller and the validation performance first increases and then decreases, you can say the model training is facing the overfitting issue.
This means there is no need to continue the training process unless you have a solution (e.g., add more data) to the overfitting issue. And if you have an elegant training strategy, the model performance may be further improved.

I did not tune the settings separately on each dataset for better performance. 
I just set the default `epochs` as `2000` for all three datasets. The settings of other hyperparameters also matter, _e.g._, `args.decay_interval = int(args.epochs/10)`.
For this dataset, smaller `epochs` may be enough if no elegant solution to the overfitting issue.
However, you should also take a look at the curves on the other two datasets.
For the other two datasets, `epochs>2000` may obtain a better performance, which means the model did not reach the perfect convergence state in the **default** settings.

**Comment by stillbetter** [comment]
Great！Thanks for the enthusiastic and patient answner.I'll bother if any question again.
