### ISSUE TITLE
CUDA out of memory when testing my own datasets

### ISSUE THREAD

**Issue by stillbetter** [lidq92/VSFA#17]
Hi Dr. Li. Sorry for a third question. When I want to test a self-collected datasets, the test_demo.py give a error feedback that memory is not enough

`RuntimeError: CUDA out of memory. Tried to allocate 676.00 MiB (GPU 0; 10.76 GiB total capacity; 1.04 GiB already allocated; 602.56 MiB free; 1.56 GiB reserved in total by PyTorch)`

I would guess my video resolution caused this with a 1080*1920 ,however, even the provided `test.mp4` get the same error.
![image](https://user-images.githubusercontent.com/42489440/82229273-ce92f580-995c-11ea-9c6b-399e9f3ba2e0.png)

I want to know if the all the tests are right in your experiments with any resolution videos?

Thank you!

**Comment by lidq92** [comment]
See #12
