### ISSUE TITLE
求KoNViD-1k和LIVE-Qualcomm数据集下载链接

### ISSUE THREAD

**Issue by upupbo** [lidq92/VSFA#18]
前辈您好，现在这两个数据集下载链接失效了，您可以帮忙提供一下百度云下载链接嘛，谢谢您

**Comment by lidq92** [comment]
@upupbo 这两个链接应该都是没有失效的，只是你的网络能不能访问的问题。

如果你实在没办法的话，可以考虑以下[百度云链接](https://pan.baidu.com/s/1o7DExgzH9yqjMH_UoqfmyA),  密码:amvg 
请遵守相应数据集的copyright协议 [KoNViD-1k](database.mmsp-kn.de/konvid-1k-database.html), [LIVE-Qualcomm](https://live.ece.utexas.edu/research/incaptureDatabase/index.html)

**Comment by liu0527aa** [comment]
十分感谢 能否再提供一下CVD2014的百度云地址连接~

**Comment by lidq92** [comment]
@liu0527aa #1

**Comment by liu0527aa** [comment]
由于在该链接下载十分缓慢且易中断 希望能提供百度云分享下载

**Comment by lidq92** [comment]
@liu0527aa 链接:https://pan.baidu.com/s/1yb1NT9xKqXRFkG8v_kBeWg  密码:k3uq
请自觉遵守该数据集的copyright协议

**Comment by lidq92** [comment]
@richardmillions1996

**Comment by lidq92** [comment]
@ciwei123
