### ISSUE TITLE
跨数据库测试

### ISSUE THREAD

**Issue by liu0527aa** [lidq92/VSFA#19]
你好，我注意到论文中并未涉及跨数据库的训练测试。本算法是否有进行过跨数据库的数据测试？

**Comment by lidq92** [comment]
@liu0527aa 会议版本没有做跨数据集评估，我们在扩展的期刊版本中做了相关实验，实验结果表明在单个数据集训练其他数据集测试的跨数据集评估设置下，几乎所有的模型都不work。这是由于不同数据集之间的数据分布差异太大以及数据集规模太小模型容易过拟合到当前数据集造成的，所以我们在扩展工作中考虑了混合数据集训练来一定程度缓解过拟合。可以看一下下图的一个结果，文章还在投稿中，所以相关内容暂时未公布。

<img width="901" alt="image" src="https://user-images.githubusercontent.com/22191442/87900527-3235be00-ca87-11ea-8312-84f04fd86cb1.png">

**Comment by liu0527aa** [comment]
十分感谢解答，另外由于显存限制，CNN特征提取时，采用不同的 frame_batch_size，是否会影响最终的SRCC？本论文得到的数据采用的 frame_batch_size都是默认64吗？

**Comment by lidq92** [comment]
@liu0527aa 没影响，越小提取特征越慢，显存不够可以设置为1.
我的显存的话提取LIVE-Qualcomm可以用` frame_batch_size=8`，可以看特征提取代码中6-8行的注释。
