### ISSUE TITLE
您好，请问您的数据集是如何下载的？

### ISSUE THREAD

**Issue by cassiaaaaaa** [lidq92/VSFA#2]
我发送了申请，但是返回的地址打不开...

**Comment by lidq92** [comment]
@cassiaaaaaa CVD2014现在的链接下载无效了，有效下载方案可以看上一个[issue](https://github.com/lidq92/VSFA/issues/1)  #1  

[KoNViD-1k]http://database.mmsp-kn.de/konvid-1k-database.html)

[LIVE-Qualcomm](http://live.ece.utexas.edu/research/incaptureDatabase/index.html)，最后返回的地址估计是要挂vpn才能下载。

**Comment by cassiaaaaaa** [comment]
非常感谢!

---原始邮件---
发件人: "李鼎权, Dingquan Li"<notifications@github.com>
发送时间: 2019年8月19日(星期一) 晚上10:53
收件人: "lidq92/VSFA"<VSFA@noreply.github.com>;
抄送: "Mention"<mention@noreply.github.com>;"cassiaaaaaa"<120384092@qq.com>;
主题: Re: [lidq92/VSFA] 您好，请问您的数据集是如何下载的？ (#2)



@cassiaaaaaa CVD2014现在的链接下载无效了，有效下载方案可以看上一个issue  #1
 
[KoNViD-1k]http://database.mmsp-kn.de/konvid-1k-database.html)
 
LIVE-Qualcomm，最后返回的地址估计是要挂vpn才能下载。
