### ISSUE TITLE
hyper-parameters & motion-related features

### ISSUE THREAD

**Issue by liu0527aa** [lidq92/VSFA#20]
你好，我注意到论文中的FC层的设置为先通过全连接FC 4096->128 后 RELU+dropout 再全连接FC 32->32  。 这样设置是有什么依据吗？ 是否尝试过在GRU之后回归得分时采用类似操作来提升性能？

**Comment by lidq92** [comment]
@liu0527aa 我没有再去把网络弄这么复杂，也没有去做太多超参数的选择，4096->128->32这些数字的选取主要是基于信息不要丢失太多以及网络参数量不要太多这两点考虑的。

4096->128只是为了降维以降低GRU训练难度(请注意4096->128之后并没有加relu和dropout, 你看到的代码里ANN要是多层感知机的时候才有relu和dropout，这是因为我以前的投稿中曾做过实验将降维模块改为非线性的多层感知机，但并没有什么提升。因为在后续投稿中加入了新的内容，所以就把这部分的实验去掉了)。
之后GRU的input size=128, hidden size=32，且用ht直接作为特征进行回归32->1, 并没有你提问中的32->32的这个过程，你可能还是需要仔细看看论文和代码。当然，这个32->1的回归模块可以改成多层感知机，这些超参数也可以作一些修改，但我没有试过有没有提升，我估计有提升的话也不会很大吧，而且这点小改变称不上有novelty，作为入门的新手去体验一下还行，但是如果已经入门的话，建议还是把时间和精力放在其他更关键的问题研究上吧。

**Comment by liu0527aa** [comment]
十分感谢你的耐心解答。对于论文中所提到的引入Motion information，我十分感兴趣，能否提供用于加入运动信息后的内容提取代码？

**Comment by lidq92** [comment]
@liu0527aa 论文里那部分的内容做的实验是当前的内容相关的特征和运动相关的特征拼接作为最后的特征。内容相关的特征提取就是在`CNNfeatures.py`文件中，按照文中的[7,22]这两篇引用其实你可以直接找到运动相关特征提取的代码，即用初始化的[TVnet](https://github.com/LijieFan/tvnet)提光流，并根据文章[22]中的公式计算光流特征，具体计算可以参见 [FLOSIM](http://www.iith.ac.in/~lfovia/Codes/FLOSIM.zip)提取相关代码即可。

**Comment by liu0527aa** [comment]
FLOSIM 已尝试向作者发送请求压缩密码 但仍未回复 能否提供一下压缩密码？

**Comment by lidq92** [comment]
@liu0527aa It can be used only for research purposes. And you can contact the authors of FLOSIM if you have any questions (To get the email address, see the following figure).

<img width="900" alt="image" src="https://user-images.githubusercontent.com/22191442/90495467-3f71c580-e177-11ea-8662-4a6dbc7bc9ca.png">
