### ISSUE TITLE
时间记忆效应参数选择

### ISSUE THREAD

**Issue by liu0527aa** [lidq92/VSFA#21]
你好，我回顾了一下《TEMPORAL HYSTERESIS MODEL OF TIME VARYING SUBJECTIVE VIDEO QUALITY》。发现原论文对于时间记忆模型的参数最优选择为tau=2s，beta=0.8.而本论文中采用的tau=12，beta=0.5并不一致。是否有尝试过采用原文里的最佳参数，或者是说是因为本参数的选择与视频数据库的选择有极强的相关性。

**Comment by lidq92** [comment]
@liu0527aa See Figure 5 of the paper for other choices of tau and gamma. 
We did not report the results with "tau=2s and gamma=0.8". You may have a try.
However, you should know that different videos on a dataset may have different frame rates.
