### ISSUE TITLE
VSFA's Performance comparision with VIIDEO

### ISSUE THREAD

**Issue by stillbetter** [lidq92/VSFA#22]
Hi, Dr.Li:

I find there's a performance comparision with VIIDEO in **Table 1**. But the VIIDEO algorithm needs luminance as input according to the released code from LIVE.

 I want to know if you just transformed the .mp4 file into .yuv and then send it to VIIDEO? Would this cause any disturbance to the final result?

Thanks a lot!

**Comment by lidq92** [comment]
@stillbetter For the video with RGB format, we used the MATLAB functions `VideoReader, readFrame, rgb2gray` to get its luminance component (See below). We did not try pre-processing the video to YUV format first.
```matlab
v = VideoReader(vidname);
count        = 1;
while hasFrame(v)
    ydis1 = double(rgb2gray(readFrame(v)));
    try
        ydis2 = double(rgb2gray(readFrame(v)));
    catch
        break;
    end
    [feat]                  = computeVIIDEOfeaturevector(ydis1,ydis2,...
                              blocksizerow,blocksizecol,blockrowoverlap, ...
                              blockcoloverlap,filtlength);
    param(count).featvect   = feat;
    count                   = count +1;

end
```

**Comment by stillbetter** [comment]
Great！Thanks for the instant help!
