### ISSUE TITLE
Pretrained Weights

### ISSUE THREAD

**Issue by lovekittynine** [lidq92/VSFA#23]
Thanks for your great work! Could you provide the pretrained weight using LIVE-Qualcomm dataset? Thanks very much!

**Comment by lidq92** [comment]
@lovekittynine "The model weights provided in `models/VSFA.pt` are the saved weights when running the 9-th split of KoNViD-1k."
You may also have other trained model weights with a different split of a different dataset.

Do you have difficulty in running the training code?
- If no, I would suggest you just run the training code first to train a model on LIVE-Qualcomm dataset (with any `exp_id` or with your own train-val-test split if you want).
- If yes, please reply to me here.

**Comment by lovekittynine** [comment]
Thanks for your answer! I can't download LIVE-Qualcomm dataset, in this paper, you have provided an impressive result on LIVE-Qualcomm dataset. So, I want to test my own dataset with weights pretrained on LIVE-Qualcomm, maybe it is more suitable for my own dataset. Of course, I have tried pretrained weights with KoNViD-1k, BUT it performs poorly! Thank you very much!

**Comment by lidq92** [comment]
@lovekittynine If you think that your dataset is more similar to the LIVE-Qualcomm dataset, you may want to download it to do more things (Refer to #18).

You should be aware of the discrepancy of data distribution among the datasets, which may cause poor performance in the cross-dataset evaluation setting. This is a common problem for the existing models (including ours). We have extended this work to address this problem to some extent, and the extended work is currently under Major Revision of IJCV Special Issue on Computer Vision in the Wild. We will make this extended work available once it is peer-reviewed. 

For now, I have the following two suggestions for you.
First, you can download the LIVE-Qualcomm and utilize this annotated dataset, then analyze the dataset and make your train-val-test split for re-training the VSFA model on the LIVE-Qualcomm, finally, you test the trained model on your own dataset (The model [as well as other VQA models] may also perform poorly on your dataset in such situation if your own dataset has a different distribution in comparison to the trained dataset.). You may try to improve the models (e.g., with the knowledge of domain adaptation).
Second, you can make a more suitable dataset for your application. That is, you collect the videos from your application and annotate their quality scores, then train the VSFA model ( or other models) with your constructed dataset. In this way, I guess you would get better performance for your test application.

For free to drop comments here if you still have any problem (It would be quite easy to get the model weights trained on LIVE-Qualcomm once you have downloaded the dataset).

**Comment by lovekittynine** [comment]
Thanks very much, I will try it!

**Comment by lovekittynine** [comment]
Sorry to trouble you again, could you please provide a download link for CVD2014 database (maybe baidu disk link). I have tried many times using the link provided in paper and answers in issue, but it failed!

**Comment by lidq92** [comment]
@lovekittynine See https://github.com/lidq92/VSFA/issues/18#issuecomment-654929656 for the Baidu disk link for downloading CVD 2014.
