### ISSUE TITLE
Question about V-BLIINDS&NIQE

### ISSUE THREAD

**Issue by stillbetter** [lidq92/VSFA#24]
Hi Dr.Li:

I notice you used NIQE and V-BLIINDS(needs NIQE as  part of feature) as the compared methods. 

I want to know if you tested with the default setting _(125 pristine images with patch size set to 96X96 and sharpness threshold of 0.75_) or you retrained and got new NIQE parameters? 

Thanks!

**Comment by lidq92** [comment]
@stillbetter I use the default parameters of NIQE.
NIQE obtains a video score by average the frame-level scores, while VBLIINDS obtains a video score with a re-trained SVR model on the same training set.

**Comment by stillbetter** [comment]
Got it！Thanks！
