### ISSUE TITLE
Loss Function!

### ISSUE THREAD

**Issue by lovekittynine** [lidq92/VSFA#25]
Hi, I found a new paper which was aimed at IQA used a novel loss function named 'Norm in Norm'. Yeah, it's a great new work belongs to you and your team, I wonder know weather it is evaluated in VQA case?

**Comment by lidq92** [comment]
@lovekittynine A special case is used in the extension of VSFA.
However, it is not the main focus of that work.
The submission of that work is currently in major revision, and I would release the code in the future, maybe next year if the following review process is lucky enough.

**Comment by lidq92** [comment]
The relevant code is now released at [MDTVSFA](https://github.com/lidq92/MDTVSFA).
