### ISSUE TITLE
The question about GRU setting

### ISSUE THREAD

**Issue by liu0527aa** [lidq92/VSFA#27]
我注意到你使用GRU模块将128维降维至32。这块对于GRU的设置处理是怎么思考的，GRU的降维是否会导致部分信息的损失？

**Comment by lidq92** [comment]
@liu0527aa 降维是会丢失信息，但是这个网络从输入到输出本来就是在丢失次要信息留下主要信息的过程呀，没明白你有疑问的点在哪里。

GRU模块的超参数我没用验证集去选择，就是简单设置的，从128->32就是兼带降维，你也可以试试128->128, 或者甚至是升维，但是升维的操作在这个问题里是不常见的。
