### ISSUE TITLE
Question about CORNIA

### ISSUE THREAD

**Issue by liu0527aa** [lidq92/VSFA#28]
论文中所提到的CORNIA算法，我尝试过寻找开源代码，但并未找到。能否提供一下V-CORNIA的开源出处。十分感谢

**Comment by lidq92** [comment]
@liu0527aa 我论文里对比的是CORNIA, 网上很多地方都能下载到代码，当然原作者也提供了下载链接[CORNIA_release_v0](http://www.umiacs.umd.edu/~pengye/research/CORNIA_release_v0.zip)，我就不额外上传了。另外，简单关键词搜一下就出来alternative的下载链接了 [tu184044109/BVQA_Benchmark](https://github.com/tu184044109/BVQA_Benchmark)，你也可以看看里面的一些其他代码的下载。CORNIA一作的GitHub是[deerzq](https://github.com/deerzq)。
V-CORNIA我没有源码，一作现在可能不活跃在学术界了，主页和Google学术都没有什么更新了，你可以参照CORNIA和V-CORNIA的论文（bibtex信息见下面）实现。

@inproceedings{xu2014no,
  title={No-reference video quality assessment via feature learning},
  author={Xu, Jingtao and Ye, Peng and Liu, Yong and Doermann, David},
  booktitle={IEEE International Conference on Image Processing},
  pages={491--495},
  year={2014},
  organization={IEEE}
} % V-CORNIA
