### ISSUE TITLE
video_names

### ISSUE THREAD

**Issue by crqqq** [lidq92/VSFA#3]
您好，请问下载的KoNViD-1k数据集内视频的名字与加载的video_names（8424428827_original_centercrop.mp4）名称不一导致找不到文件是什么原因?

**Comment by lidq92** [comment]
@crqqq 我下载的数据集是他重命名之前的，显示的是8424428827_cut_centercrop_960x540_8s.mp4, 你现在下他的meta-files还是用的这样的命名方式。在[Dropbox browse videos](https://www.dropbox.com/sh/tp0m4k62x3km5ml/AAAltkOFD7Ob7glsqxMAJC5La?dl=0&lst=)也是这个名字，我也看了一下现在下载下来的数据集名字改成flicker_id.mp4了，你说的情况可能是他中间修改的情况。。。我已经把相关情况截图到这个链接了（链接:https://pan.baidu.com/s/14RpNWaYsx1nm_WjvZ6BdTA  密码:uwjs 有效期7天）

你自己用flicker_id来对应上你下载的这些视频吧，很简单的。或者你懒的话，就自己询问数据库的作者能不能直接给你修改前后的映射。
再或者我在上面这个链接也分享我下载的未修改名字的版本，你也可以再下载一次。

**Comment by crqqq** [comment]
感谢您的解答，您所说的那个命名8424428827_cut_centercrop_960x540_8s.mp4是正确的，我记错了，非常抱歉
