### ISSUE TITLE
Performance on LIVE-VQC

### ISSUE THREAD

**Issue by vztu** [lidq92/VSFA#31]
Hi Dingquan, I am wondering do you have the results on LIVE-VQC [1]? I'd like to simply refer to your results, if available, such that I don't need to test by myself. Thanks!

[1] Z.  Sinno and  A.  C.  Bovik,  “Large-scale study of perceptual video quality,” IEEE Trans. Image Process., vol. 28, no. 2, pp. 612–627, 2018

**Comment by lidq92** [comment]
@vztu Hi Zhengzhong, thank you for your interest.
Currently, I do not have the results of VSFA on LIVE-VQC. 
You may refer to [MDTVSFA](https://github.com/lidq92/MDTVSFA) for results of LS-VSFA and MDTVSFA (improved models of VSFA) on LIVE-VQC.

I have left PKU, and I just got the connection to the desktop. 
If you are not in a hurry, you can wait for my experimental results of VSFA on LIVE-VQC.
You may remind me 2 days later in case I forget to update the results for you.

By the way, if you are using different train-val-test splits, it would be better to compare different methods under your train-val-test splits.

**Comment by vztu** [comment]
Hi @lidq92, thanks for your replies and happy new year!

I did check your MDTVSFA, specifically in Table 6, but didn't find the train-test results of VSFA on LIVE-VQC. Table 5 did contain LS-VSFA but did not include LIVE-VQC. Please let me know whether I missed it.

It would be great if you can append the results of VSFA on LIVE-VQC on your VSFA Github repo or elsewhere, but you can just take your time cause I am not in a hurry. It would be very useful if you could also follow the formats of mean (std) as shown in https://github.com/lidq92/VSFA#reproduced-results.

**Comment by lidq92** [comment]
@vztu Happy new year, too!

I would update the results in [VSFA#reproduced-results](https://github.com/lidq92/VSFA#reproduced-results).
I just realized 2000 epochs may take too much training time, and I am currently set the epoch number to 300 and re-run the experiments.

**Comment by vztu** [comment]
Hi thanks, take your time

**Comment by lidq92** [comment]
@vztu The results of VSFA on LIVE-VQC (when I set epochs=300) are shown as follows.

And the train-val-test splits information is from [here](https://github.com/lidq92/MDTVSFA/blob/main/data/LIVE-VQCinfo.mat). The `exp_id` ranges from 0 to 9.

`SROCC: 0.6978±0.0340 KROCC: 0.5094±0.0312 PLCC: 0.7426±0.0404 RMSE: 11.6495±0.7385`

**Comment by vztu** [comment]
Thanks @lidq92!
