### ISSUE TITLE
有关 Content-Aware Feature Extraction部分的spatial global average pooling operation的问题

### ISSUE THREAD

**Issue by lllllllllllll-llll** [lidq92/VSFA#35]
您好！Content-Aware Feature Extraction部分的池化操作不仅用了全局平局池化也用了这个global average pooling operation，这个池化是全局标准差池化的意义是啥呢，求解。为什么不用全局平均池化和全局最大池化呢，会不会效果更好呢？谢谢解答。

**Comment by lidq92** [comment]
把patch feature的每一个维度当作是一个随机变量，N个patches对应feature维度的取值可以当作是观测值，那么你就有了一个离散分布。要去描述或者说summarize这个离散分布，可以用它的统计量。如果这个分布接近高斯，那么均值和标准差来描述就很合适了。关于这个pooling/aggregation可以看Which Has Better Visual Quality: The Clear Blue Sky or a Blurry Animal? 这篇文章中的论述。

用均值和最大值来描述一个分布的情况不太好理解，所以我没试过这么做。

**Comment by lidq92** [comment]
把patch feature的每一个维度当作是一个随机变量，N个patches对应feature维度的取值可以当作是观测值，那么你就有了一个离散分布。要去描述或者说summarize这个离散分布，可以用它的统计量。如果这个分布接近高斯，那么均值和标准差来描述就很合适了。关于这个pooling/aggregation可以看Which Has Better Visual Quality: The Clear Blue Sky or a Blurry Animal? 这篇文章中的论述。

用均值和最大值来描述一个分布的情况不太好理解，所以我没试过这么做。

**Comment by lllllllllllll-llll** [comment]
谢谢讲解，我去看看您的论文
