### ISSUE TITLE
请问数据读取是否有问题呢？

### ISSUE THREAD

**Issue by ma3252788** [lidq92/VSFA#36]
`ref_ids = Info['ref_ids'][0, :]`请问这里是不是有问题？因为info['ref_ids']是(n,1)，所以如果`ref_ids = Info['ref_ids'][0, :]`这样的话，读取的只是一个数，这样后面都会乱了。

我修改成`ref_ids = Info['ref_ids'][:, 0]`，然后训练之后，发现结果一直是不对的。请问大神，您知道这是怎么回事吗？

![](https://ypyssl.machunjie.com/machunjie/20210522104719.png)

**Comment by lidq92** [comment]
@ma3252788 这个请你自己print一下ref_ids = Info['ref_ids'][0, :]后就知道了，你改了之后才是一个数。
