### ISSUE TITLE
模型问题

### ISSUE THREAD

**Issue by crqqq** [lidq92/VSFA#4]
作者您好，在我复现您的代码出现了几个问题
1、执行您的源码时发现models路径下并不存在代码中train_model_file所需的名为VSFA-KoNViD-1k-EXP0的模型，
2、当我将此变量更换为使用models内原有的VSFA.pt时，使用默认学习率训练，结果出现SROCC、KROCC、PLCC均为nan，RMSE为0.625的情况，在将学习率调低之后，使用了权重衰减再次训练仍然出现此情况
3、请问训练结束后的模型是直接更新了原有的VSFA.pt吗

**Comment by lidq92** [comment]
@crqqq 
请你不要混淆了`test_demo.py`和`VSFA.py`这两个文件的用途，请认真阅读readme.

1. trained_model_file是训练时保存文件用的，一开始并不存在，之后保存的
2. 我没理解为什么会有更换的说法，你更换了哪里的东西？？请看readme操作.
3. VSFA.pt是我提供给test demo展示这个方法输入输出应该是怎样用的。你可以理解为我训练完之后的一个模型VSFA-database-EXPk重命名之后得到的VSFA.pt

最后，阅读readme能教你怎么操作train和test，但是如果你要改代码请一定要把原有的代码都看完，才知道你自己改的对不对。

如果还有问题的话请将你的问题描述得更准确些。
