### ISSUE TITLE
视频文件读取问题

### ISSUE THREAD

**Issue by hrf666666** [lidq92/VSFA#48]
在载入大文件视频时会存在内存溢出或者cuda显存溢出问题，希望作者可以改进io这里的方法，分批次读取并推理得分

**Comment by lidq92** [comment]
`CNNfeatures.py`中有一个参数是`frame_batch_size`，极端情况下可以设置为1，占用的内存/显存最小。我在这个文件一开始的注释那里写了三个数据集对应的`frame_batch_size`取值，在当时一个普通的1080上就可以提取的，更不用说现在的4090或者V100啦。
