### ISSUE TITLE
Missing CNN_features_KoNViD-1k/1_resnet-50_res5c.npy

### ISSUE THREAD

**Issue by B0rschti** [lidq92/VSFA#5]
By running the command:

1. CUDA_VISIBLE_DEVICES=0 python VSFA.py --database=KoNViD-1k --exp_id=0

A error is thrown that the file or directory "CNN_features_KoNViD-1k/1_resnet-50_res5c.npy" is missing (FileNotFoundError)

Can you please add this file or provide a link to download it.
Thanks in advance.

Here the terminal log
`
$ CUDA_VISIBLE_DEVICES=0 python VSFA.py --database=KoNViD-1k --exp_id=0
EXP ID: 0
KoNViD-1k
VSFA
Traceback (most recent call last):
  File "VSFA.py", line 161, in <module>
    train_dataset = VQADataset(features_dir, train_index, max_len, scale=scale)
  File "VSFA.py", line 30, in __init__
    features = np.load(features_dir + str(index[i]) + '_resnet-50_res5c.npy')
  File "/<SOME_PATH>/numpy/lib/npyio.py", line 428, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'CNN_features_KoNViD-1k/1_resnet-50_res5c.npy'
`

**Comment by lidq92** [comment]
@
