### ISSUE TITLE
Which database is the pre-trained model(VSFA.pt) based on ?

### ISSUE THREAD

**Issue by RigoYao** [lidq92/VSFA#7]
Hi! I notice that there is a pre-trained model file 'VSFA.pt' in the directory 'models'.
Could you please tell me which database is the pre-trained model trained on?
Thank you so much.

**Comment by lidq92** [comment]
@RigoYao It is trained on KonViD-1k. You can also refer to our `VSFA.py` file to train a new model for your data.

**Comment by lidq92** [comment]
@RigoYao I update the code. You can get more details on how to get the `VSFA.pt`
