### ISSUE TITLE
测试分数为负数值

### ISSUE THREAD

**Issue by CabbageWust** [lidq92/VSFA#9]
您好，我用您的模型测试一些视频文件的时候发现会出现一些结果为负数的情况。另外我看到您是最近在get_features()函数中添加了 extractor.eval() 这句话 ，删除这句话后， 测试结果中没有负数值， 整体结果也比较好。extractor.eval()这句究竟该不该要。。。

**Comment by lidq92** [comment]
@CabbageWust 抱歉，我更新了一下代码，忘记把其他相应的传上来了。我现在就传上来。

**Comment by lidq92** [comment]
@CabbageWust 另外需要说明的一点是，我训练的时候把mos转label的时候是直接除以mos最大值，并不是线性的scale到[0,1], 这样的话在CVD2014的labels本身就有负数。

还有就是模型并没有限制输出要是非负的。举个例子，拿KoNViD-1k数据进行训练的时候，即便labels都是正的，也不能保证随便输入一个测试视频输出的预测质量分数是正的。这一点你应该能理解吧。
甚至极端点说，模型没训练好的时候，即便输入一个训练集的视频进去也存在输出是负数的可能。
